name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
        sudo apt update && sudo apt install -y cmake make gcc ibasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

    - name: Build raylib
      run: |
        git clone https://github.com/raysan5/raylib.git --depth=1
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install
      
    - name: pre-build
      run: gcc nob.c -o nob
    - name: build
      run: ./nob
